---
title: "My Final Project Template"
author: Sunny
subtitle: "The relationship between crime rate and socio-economic variables: in the case of New York City"
output:
  html_document:
    keep_md: true 
---

# Introduction

[~ 200 words]   

Crime is an important socio-economic problem affecting everyone’s life. Large cities such as New York City and Los Angeles, where have a high density of population and a mixture of ethnicities are often have a higher crime rate. Moreover, crimes may occur from multiple reasons and background. Different socio-economic status such as income, education level, ethnicities and age could urge people to commit crimes due to different reasons. Hence, it is confirmed that there are certain connections between crime rate and socio-economic variables.

New York City is the largest city in USA, which has the largest population is often seen as a dangerous and unsafe region where people feel insecure to walk alone at night in certain area. Certain regions in NYC are seen relatively dangerous comparing with others, such as Brownsville, Midtown and Bedford area. The region mentioned above are areas considered dangerous places in the city. Therefore, it is obvious that there is a certain spatial pattern among the crimes that happened in NYC.


# Materials and methods

[~ 200 words]

The study area in this study will be the entire New York City, which included 5 surrounded counties: New York County, Kings County, Queens County, Bronx County Richmond County. 

The polygon data will be the census tract in NYC region, which includes 2167 census tracts in total. Each census tract will include its respective socio-economic variables, such as: Education level in each age group, housing variables, gini Index (income and wealth equality), median income, median age, ethnicities proportion, unemployed rate.The socio-economic variables data was originaly a csv file downloaded from the  US census Bureau, and merged with the polygon data in R afterwards.

The crime data is originally downloaded from NYPD. Which is the point data of all the crimes committed in 2021 with its longitude and latitude included. In order to know how many crimes happened in each census tract, the points of crimes in each polygon will be counted, and set as the number of crimes of the respective census tract.  

Load any required packages in a code chunk (you may need to install some packages):

